creteng.ostlive.com_Sep28/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('comingSoon');
})->name('comingSoon');

Auth::routes();

Route::group(['middleware' => ['auth','is_admin']], function() {
	
	Route::get('/admin/dashboard', 'HomeController@adminHome')->name('dashboard');
	
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
  
	Route::get('/admin/users/edit/{users}','UserController@edituser')->name('userEdit');
	Route::post('/admin/users/update/{users}','UserController@updateuser')->name('userFormUpdate');
    Route::post('/admin/users/status', 'UserController@changeStatus')->name('userChangeStatus');
	Route::get('/admin/password/edit/{user}','UserController@adminpasswordedit')->name('adminPasswordEdit');//
	Route::post('/admin/password/update/{user}','UserController@adminpasswordupdate')->name('adminPasswordUpdate');//
	
});
		

creteng.ostlive.com_Sep28/resources/views/admin/layouts/sublayouts/sidebar.blade.php
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index.html" class="brand-link">
      @php 
      $superadmin=env("APP_SUPERADMIN"); 
      $managers=env("APP_MANAGER");
      @endphp
      @if(Auth::user()->hasRole($superadmin))
      <span class="brand-text font-weight-light">Administrator</span>
      @endif
      @if(Auth::user()->hasRole($managers))
      <span class="brand-text font-weight-light">Manager</span>
      @endif
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          
          @if(Auth::user()->hasRole($superadmin))
          <li class="nav-item has-treeview menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Super Admin
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('users.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Manage Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('roles.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Manage Roles</p>
                </a>
              </li>
            </ul>
          </li>
          @endif
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              @if(Auth::user()->hasRole($superadmin))
              <p>
                Admin Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
              @endif
              @if(Auth::user()->hasRole($managers))
              <p>
                Manager Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
              @endif
            </a>
            <ul class="nav nav-treeview">
              
              @php $user_id = Auth::user()->id; @endphp
              @if(isset($user_id))
              <li class="nav-item">
                <a href="{{ route('adminPasswordEdit', $user_id) }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Change Password</p>
                </a>
              </li>
              @endif
            </ul>
          </li>

          
		</ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

creteng.ostlive.com_Sep28/resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="container">
	
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
			<a href="{{ route('allUsers') }}"><button type="button" class="btn btn-secondary">Go back to Users</button></a>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>	
    			
	@if(Session::has('success'))
		<div class="alert alert-success">
			{{ Session::get('success') }}
            @php
                Session::forget('success');
            @endphp
        </div>
    @endif
	
	<div class="card">
		<div class="card-body">
			<form method="POST" id="fieldgroup-form" action="{{ route('userForm') }}">
			{{ csrf_field() }} 
			  <div class="form-group">
				<label for="name">Name</label>
				<input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
					@if ($errors->has('name'))
						<span class="text-danger">{{ $errors->first('name') }}</span>
					@endif
			  </div>
			  <div class="form-group">
				<label for="name">Email</label>
				<input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required autocomplete="email">
					@if ($errors->has('email'))
						<span class="text-danger">{{ $errors->first('email') }}</span>
					@endif
			  </div>
			<div class="form-group">
				<label for="country_code">{{ __('Contact No') }}</label>
				<div class="row">
				<div class="col-md-2">
					<input id="country_code" type="text" class="form-control @error('country_code') is-invalid @enderror" name="country_code" value="{{ old('country_code') }}" required autocomplete="country_code">
					<small class="form-text text-muted">Country Code</small>
					@error('country_code')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				<div class="col-md-4">
					<input id="contact" type="text" class="form-control @error('contact') is-invalid @enderror" name="contact" value="{{ old('contact') }}" required autocomplete="contact">
					@error('contact')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				</div>
			</div>
			  <div class="form-group">
				<label for="password">Password</label>
				<input type="password" class="form-control" id="password" name="password" required autocomplete="new-password">
					@if ($errors->has('password'))
						<span class="text-danger">{{ $errors->first('password') }}</span>
					@endif
			  </div>
			  <div class="form-group">
				<label for="password-confirm"> Confirm Password</label>
				<input type="password" class="form-control" id="password-confirm" name="confirm-password" required autocomplete="new-password">
			  </div>
			  <div class="form-group">
				<label for="roles">Roles</label>
					{!! Form::select('roles[]', $roles,[], array('class' => 'form-control')) !!}			  
				</div>
			  <button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
	
</div>
@endsection

creteng.ostlive.com_Sep28/resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="container">
	
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
			<a href="{{ route('dashboard') }}"><button type="button" class="btn btn-secondary">Go back to Dashboard</button></a>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>	
    	
	@if(Session::has('success'))
		<div class="alert alert-success">
			{{ Session::get('success') }}
            @php
                Session::forget('success');
            @endphp
        </div>
    @endif
	
	<div class="card">
		<div class="card-body">
			<form method="POST" id="user-form" action="{{ route('userFormUpdate', $user->id) }}">
			{{ csrf_field() }} 
			  <div class="form-group">
				<label for="name">Name</label>
				<input type="text" class="form-control" id="name" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>
					@if ($errors->has('name'))
						<span class="text-danger">{{ $errors->first('name') }}</span>
					@endif
			  </div>
			  <div class="form-group">
				<label for="name">Email</label>
				<input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}" required autocomplete="email">
					@if ($errors->has('email'))
						<span class="text-danger">{{ $errors->first('email') }}</span>
					@endif
			  </div>
			<div class="form-group">
				<label for="country_code">{{ __('Contact No') }}</label>
				<div class="row">
				<div class="col-md-2">
					<input id="country_code" type="text" placeholder="91" class="form-control @error('country_code') is-invalid @enderror" name="country_code" value="{{ $user->country_code }}" required autocomplete="country_code">
					<small class="form-text text-muted">Country Code</small>
					@error('country_code')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				<div class="col-md-4">
					<input id="contact" type="text" placeholder="9876543210" class="form-control @error('contact') is-invalid @enderror" name="contact" value="{{ $user->contact }}" required autocomplete="contact">
					@error('contact')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				</div>
			</div>
			  <div class="form-group">
				<label for="password">Password</label>
				<input type="password" class="form-control" id="password" name="password" autocomplete="new-password">
					@if ($errors->has('password'))
						<span class="text-danger">{{ $errors->first('password') }}</span>
					@endif
			  </div>
			  <div class="form-group">
				<label for="password-confirm">Confirm Password</label>
				<input type="password" class="form-control" id="confirm-password" name="confirm-password" autocomplete="new-password">
			  </div>
			  
			  <button type="submit" class="btn btn-primary">Update</button>
			</form>
		</div>
	</div>
	
</div>
@endsection

creteng.ostlive.com_Sep28/resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="container">
@if(Session::has('flash_message'))
    <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
@endif
	
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>All Users</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	
	@if($message = Session::get('success'))
		<div class="alert alert-success">
			<p>{{ $message }}</p>
		</div>
	@endif
	
    <section class="content">
      <div class="row">
        <div class="col-12">
			
			
          <div class="card">
            <div class="card-header">
              <h3 class="card-title"></h3>
				<a class="btn btn-success" href="{{ route('createUser') }}"> Create New User</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="userdata" class="table table-bordered table-striped">
                <thead>
                <tr>
				          <th>Id</th>
                  <th>User Name</th>
                  <th>Email</th>
                  <th>Roles</th>
                  <th>Blocked</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
			@php $srno = '1'; @endphp
			@forelse($users as $user)
                <tr>
                  <td>@php echo $srno; @endphp</td>
                  <td>{{ $user->name }}</td>
                  <td>{{ $user->email }}</td>
                  <td>
					  <!-- option 1 to get user role names
					  @if(!empty($user->getRoleNames()))
						@foreach($user->getRoleNames() as $v)
						   <label class="badge badge-info">{{ $v }}</label>
						@endforeach
					  @endif  
					  -->
					  @php
						$admin=env("APP_ADMIN");
						$customers=env("APP_CUSTOMER");
            $managers=env("APP_MANAGER");
					  @endphp 
					  @foreach($user->roles->pluck('name') as $v)
						@if($v == $customers)
						<label class="badge badge-warning">{{ $v }}</label>
						@endif
						@if($v == $admin)
						<label class="badge badge-success">{{ $v }}</label>
						@endif
            @if($v == $managers) 
						<label class="badge badge-success">{{ $v }}</label>
						@endif
					  @endforeach 
					  <!-- or option 2 to get user role names  {{ $user->roles->pluck('name') }}  -->        
                  </td>
				  <td>		
					<center>
						<div class="custom-control custom-switch">
							<input type="checkbox" class="custom-control-input" id="{{ $user->id }}" data-id="{{ $user->blocked }}" {{ $user->blocked ? 'checked' : '' }}>
							<label class="custom-control-label" for="{{ $user->id }}">&nbsp;</label>
						</div>
					</center>
				  </td>
                  <td><center>
					  <!--<a href="{{ route('userShow', $user->id )}}"><button type="button" class="btn btn-primary">View</button></a>-->
					  <a href="{{ route('userEdit', $user->id )}}"><button type="button" class="btn btn-dark">Edit</button></a>
					  <!--<a href="{{ route('userDelete', $user->id )}}"><button type="button" class="btn btn-danger">Delete</button></a>-->
					  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{ $user->id }}" data-id="{{ $user->id }}" >Delete</button>
                  </center></td>
                </tr>
                
				<!-- Delete User Modal Starts -->
				<div class="modal fade" id="exampleModal{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
					  <div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Warning</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						  <span aria-hidden="true">&times;</span>
						</button>
					  </div>
					  <div class="modal-body">
						If you want to delete this user , all information will be lost of this user
					  </div>
					  <div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
						<a href="{{ route('userDelete', $user->id )}}"><button type="button" class="btn btn-danger">Yes, go forward</button></a>
					  </div>
					</div>
				  </div>
				</div>
                <!-- Delete User Modal Ends -->
                
            @php $srno++; @endphp
            @empty
				No User Found
			@endforelse
                </tbody>
                <tfoot>
                <tr>
				  <th>Id</th>
                  <th>User Name</th>
                  <th>Email</th>
                  <th>Roles</th>
                  <th>Blocked</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

		</div>
	  </div>
	</section>
			
</div>


<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $('#userdata').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
    
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    
    $('body').on("click.bs.toggle", ".custom-control-input", function(b) {
		var status = $(this).is(":checked") == true ? 1 : 0;
		var cat_id = $(this).attr('id');		
		$.ajax({
            type: "POST",
            url: '{{ route("userChangeStatus") }}',
            data: {'status': status, 'user_id': cat_id},
            success: function(data){
				$('.alert-success').show();
				$('.alert-success').html(data.success);
            }
        });
    }); 
    
  });
</script>

@endsection

creteng.ostlive.com_Sep28/resources/views/comingSoon.blade.php
<!DOCTYPE html>
<html>
<style>
body, html {
  height: 100%;
  margin: 0;
}

.bgimg {
  background-image: url("{{ asset('image/photo-1507041957456-9c397ce39c97.jpg') }}");
  height: 100%;
  background-position: center;
  background-size: cover;
  position: relative;
  color: white;
  font-family: "Courier New", Courier, monospace;
  font-size: 25px;
}

.top {
  position: absolute;
  top: 10%;
  left: 40%;
  font-size: 1.5em;
  text-align: center;
}

.tagline {
  position: absolute;
  top: 30%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 0.8em;
  text-align: center;
}

.bottomleft {
  position: absolute;
  bottom: 20%;
  left: 30%;
  font-size: 1em;
}

.middle {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
  font-size: 1.5em;
}

hr {
  margin: auto;
  width: 40%;
}
</style>
<body>

<div class="bgimg">
  <div class="top">
    <p>Creteng</p>
  </div>
  <div class="tagline">
    <p>Be Creative and Challenge the World</p>
  </div>
  <div class="middle">
    <h1>COMING SOON</h1>
    
  </div>
  <div class="bottomleft">
    <p>By OpenSource Technologies </p>
  </div>
</div>

</body>
</html>

creteng.ostlive.com_Sep28/resources/views/home.blade.php
@extends('layouts.app')

@section('content')


@endsection